### ISSUE TITLE
Ng-admin as add-on for a generic application

### ISSUE THREAD

**Issue by rotober** [marmelab/ng-admin-demo#24] opened 2016-06-23 07:20 UTC
Hi, 
hope to had not miss anything but I'd like to be able to integrate an admin console in a stilll present application (kind of add-on).
Thank you
R.

**Comment by fzaninotto** [comment] 2016-06-23 09:08
Duplicate of https://github.com/marmelab/ng-admin/issues/335

**Closed by fzaninotto** 2016-06-23 09:08 UTC
