### ISSUE TITLE
entities with parents id in the URL

### ISSUE THREAD

**Issue by sebest** [marmelab/ng-admin-demo#5] opened 2015-05-30 08:26 UTC
Hello,

I have API URL like /accounts/:account/applications/:application/tasks/:task/attempts and don't see how to handle this kind of URL with ng-admin.

Any idea?

thanx

**Comment by fzaninotto** [comment] 2015-06-01 08:38
Duplicate of https://github.com/marmelab/ng-admin/issues/409. Please only open issues in this repo related to the demo itself. For questions and issues about ng-admin, use the ng-admin repository.

**Closed by fzaninotto** 2015-06-01 08:38 UTC
